disabled_rules: # rule identifiers to exclude from running
  - inclusive_language
included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - Example/Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example/Resources

# configurable rules can be customized from this configuration file.
# complexity of a function
cyclomatic_complexity:
  error: 60
  warning: 55
# number of lines allowed in a function
function_body_length:
  error: 50
  warning: 45
# number of parameters allowed for a function
function_parameter_count: 15
# number of lines allowed in a file
file_length:
  error: 735
  warning: 730
# number of characters allowed in a line
line_length:
  error: 200
  ignores_comments: true
  warning: 195
# Allow for types to be definied within a struct 1 level deep
nesting:
  type_level: 2
# number of lines allowed in a type declaration
type_body_length:
  error: 370
  warning: 365
