blank_issues_enabled: false
contact_links:
  - name: Usage Question
    url: https://stackoverflow.com/questions/tagged/cdyelpfusionkit
    about: Ask usage questions on Stack Overflow.
  - name: Yelp Fusion API Issue
    url: https://github.com/Yelp/yelp-fusion/issues
    about: Report Yelp Fusion API issues to the Yelp team.
  - name: Security Vulnerability
    url: mailto:contact@christopherdehaan.me
    about: Please report security vulnerabilities privately via email.
